---
- name: Install a Webserver
  hosts: all
  tasks:
   - name: Install httpd
     package:
        name: httpd
        state: present




   - name: Install PHP
     package:
        name: php
        state: present




   - name: Install lftp
     package:
        name: lftp
        state: present




   - name: Create index.html file
     copy:
        content: "Hello world"
        dest: "/var/www/html/index.html"




   - name: Start WebServer
     systemd:
        name: httpd
        state: started
        enabled: yes



